CREATE TABLE "admin" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "nama_lengkap" varchar
);

CREATE TABLE "layanan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_layanan" varchar,
  "estimasi" varchar,
  "harga_per_kg" decimal
);

CREATE TABLE "paket" (
  "no_resi" varchar PRIMARY KEY,
  "tanggal_input" timestamp,
  "nama_pengirim" varchar,
  "telp_pengirim" varchar,
  "kota_asal" varchar,
  "nama_penerima" varchar,
  "telp_penerima" varchar,
  "alamat_penerima" text,
  "kota_tujuan" varchar,
  "berat" decimal,
  "layanan" varchar,
  "isi_paket" varchar,
  "biaya" decimal,
  "status_terakhir" varchar
);

CREATE TABLE "tracking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "no_resi" varchar,
  "waktu" timestamp,
  "lokasi" varchar,
  "status" varchar,
  "keterangan" text
);

CREATE TABLE "feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_pengirim" varchar,
  "email" varchar,
  "subjek" varchar,
  "pesan" text,
  "tanggal_kirim" timestamp
);

ALTER TABLE "tracking" ADD FOREIGN KEY ("no_resi") REFERENCES "paket" ("no_resi");
